#!/bin/bash

# Robert Cudmore
# 20190421

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
echo -e "Running run from $DIR"
cd "${DIR}"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if ! type "virtualenv" > /dev/null; then
	echo '==='
	echo "=== install bImPy: Installing virtualenv"
	echo '==='
	#sudo /usr/bin/easy_install virtualenv
	pip install virtualenv
	# debian
	#sudo apt-get -qy install python-virtualenv
fi

if [ ! -d "bImPy_env/" ]; then
	echo '==='
	echo "=== install bImPy: Making Python 3 virtual environment in $PWD/bImPy_env"
	echo '==='
	if ! type "virtualenv" > /dev/null; then
		echo -e 'install bImPy: ${RED}ERROR${NC}: DID NOT INSTALL VIRTUALENV -->> ABORTING'
		exit 0
	else
		mkdir bImPy_env
		virtualenv -p python3 --no-site-packages bImPy_env
	fi
else
	echo '==='
	echo "=== install bImPy: Python 3 virtual environment already exists in $PWD/bImPy_env"
	echo '==='
fi



if [ -f "bImPy_env/bin/activate" ]; then
	echo '==='
	echo "=== install bImPy: Activating Python 3 virtual environment with 'source bImPy_env/bin/activate'"
	echo '==='
	source bImPy_env/bin/activate
else
	echo -e "${RED}ERROR${NC}: Python 3 virtual environment did not install in $PWD/bImPy_env"
	echo "Make sure virtualenv is installed and try installing again"
	exit 1
fi


echo '==='
echo "=== install bImPy: Installing required python libraries with 'pip install -r requirements.txt'"
echo '==='
pip install -r requirements.txt

pip install -e .

deactivate

echo -e "${GREEN}virtual environment is in bImPy_env${NC}. It can be activated with 'source bImPy_env/bin/activate"
echo -e "${GREEN}Install successful${NC}. Run the Analysis app with './run'"
