#!/bin/bash

# Robert Cudmore
# 20190421

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if ! type "virtualenv" > /dev/null; then
	echo '==='
	echo "=== install bStack: Installing virtualenv"
	echo '==='
	#sudo /usr/bin/easy_install virtualenv
	pip install virtualenv
	# debian
	#sudo apt-get -qy install python-virtualenv
fi

if [ ! -d "bStack_env/" ]; then
	echo '==='
	echo "=== install bStack: Making Python 3 virtual environment in $PWD/bStack_env"
	echo '==='
	if ! type "virtualenv" > /dev/null; then
		echo -e 'install bStack: ${RED}ERROR${NC}: DID NOT INSTALL VIRTUALENV -->> ABORTING'
		exit 0
	else
		mkdir bStack_env
		virtualenv -p python3 --no-site-packages bStack_env
	fi
else
	echo '==='
	echo "=== install bStack: Python 3 virtual environment already exists in $PWD/bStack_env"
	echo '==='
fi



if [ -f "bStack_env/bin/activate" ]; then
	echo '==='
	echo "=== install bStack: Activating Python 3 virtual environment with 'source bStack_env/bin/activate'"
	echo '==='
	source bStack_env/bin/activate
else
	echo -e "${RED}ERROR${NC}: Python 3 virtual environment did not install in $PWD/bStack_env"
	echo "Make sure virtualenv is installed and try installing again"
	exit 1
fi


echo '==='
echo "=== install bStack: Installing required python libraries with 'pip install -r requirements.txt'"
echo '==='
pip install -r requirements.txt

deactivate

echo -e "${GREEN}Install successful${NC}. Run the Analysis app with './run'"
