#!/bin/bash

# Robert Cudmore
# 20190421

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
echo -e "==="
echo -e "=== Running bImPy from $DIR"
cd "${DIR}"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color


if [ ! -d "bImPy_env/" ]; then
	echo '==='
	echo -e "=== ${RED}warning${NC}: virtual environment does not exist in $PWD/bImPy_env"

	#echo "=== installing with './install'"
	#./install
  	#echo '==='
	exit 1
fi


if [ -f "bImPy_env/bin/activate" ]; then
	echo "=== run: Activating Python 3 virtual environment with 'source bImPy_env/bin/activate'"
	source bImPy_env/bin/activate
fi

echo -e "=== run: running ${GREEN}'python bimpy/interface/bStackBrowser.py'${NC}"
echo -e "==="
python bimpy/interface/bStackBrowser.py
