#!/bin/bash

# Robert Cudmore
# 20190421

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
echo -e "Running bStack from $DIR"
cd "${DIR}"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color



if [ ! -d "bStack_env/" ]; then
	echo '==='
	echo -e "=== ${RED}warning${NC}: virtual environment does not exist in $PWD/bStack_env"
	echo "=== installing with './install'"
	./install
  	#echo '==='
	#exit 1
fi



if [ -f "bStack_env/bin/activate" ]; then
	echo '==='
	echo "=== run: Activating Python 3 virtual environment with 'source bStack_env/bin/activate'"
	source bStack_env/bin/activate
fi

echo "=== run: running 'python bStack.py'"
echo '==='
python bStack.py
